//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAstanaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public User()
        {
        }
        public User(int id)
        {
            this.User_ID = id;
        }

        public User(int User_ID, string Surname, string Name, string Patronymic, Nullable<System.DateTime> Birthday, 
            string Email, string Description)
        {
            this.User_ID = User_ID;
            this.Surname = Surname;
            this.Name = Name;
            this.Patronymic = Patronymic;
            this.Birthday = Birthday;
            this.Email = Email;
            this.Description = Description;
        }

    }
}
